### PR TITLE
Fixed blank space in mobile view

### LINKED ISSUE #38: Mobile version has a blank space at the bottom
When you load the web app on mobile, there's a blank space present at the bottom of every route

### Steps to reproduce:
- Use a mobile device in portrait mode
- Access https://hitec.tecoding.org/
- Observe

### Expected behaviour:
The app loads just fine and you cannot scroll down
### Actual behaviour:
The app has a blank space at the bottom of each page allowing you to scroll down

### Additional information
- Operating System: Android/iOS
- Browser: Chrome/Safari
- Branch involved: `main`

image
image
image
image
image

### PR DESCRIPTION
**Pull request by sofiadparamo**
Closes #38 

### Causes:
Mobile browsers have a search bar on top of the screen, which is calculated for the viewport metrics, using 100vh works on desktop, but not on mobile browsers due to this. A workaround is to use `position: fixed` which is the setting used here.

Learn more in [this link](https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser)

### CODE REVIEW

**Comment by sofiadparamo** [comment]
# Before approving:
 - [x] Review on at least 3 different android devices (preferably, a Tablet and two different mobile phones)
 - [ ] Review on at least 3 different iOS devices (preferably, an iPad and two different iPhones)

**Comment by sofiadparamo** [comment]
# Testers template
*Note: Please be as specific as possible, include version numbers*
 - Device model:
 - Operating system:
 - Web browser used:
 - Web browser version:
[Attach your 4 pictures]

**Comment by sofiadparamo** [comment]
Device model: Xiaomi Redmi Note 8
Operating system: Android 10, MIUI 12
Web browser used: Chrome
Web browser version: 92.0.4515.115

image
image
image
image

**Comment by GSLeonardo** [comment]
Device model: Samsung A50
Operating system: Android 11, ONE UI 3.1
Web browser used: Chrome
Web browser version: 92.0.4515.115

Landing Page
Multiple Options
Text Field
Result

**Review by AlonsoMtzG — APPROVED** [review]

**Pull request merged**
